### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by EternalRat** [AnonymusRaccoon/Bomberman#98]
Implement some power up such as :

- [x] More bomb available #39 
- [x] Speed up #30 
- [x] Increase the explosion range (+1) #29 
- [x] Bombe damage increased #72 
- [ ] Explosion can pass through walls #70
